<?php

return [
    'rows_of_passwords_list' => 10,

    // style
    'bg_styles' => [
      "bg-red",
      "bg-yellow",
      "bg-aqua",
      "bg-blue",
      "bg-light-blue",
      "bg-green",
      "bg-navy",
      "bg-teal",
      "bg-olive",
      "bg-lime",
      "bg-orange",
      "bg-fuchsia",
      "bg-purple",
      "bg-maroon",
      "bg-black",
      "bg-red-active",
      "bg-yellow-active",
      "bg-aqua-active",
      "bg-blue-active",
      "bg-light-blue-active",
      "bg-green-active",
      "bg-navy-active",
      "bg-teal-active",
      "bg-olive-active",
      "bg-lime-active",
      "bg-orange-active",
      "bg-fuchsia-active",
      "bg-purple-active",
      "bg-maroon-active",
      "bg-black-active",
      "bg-gray",
      "bg-gray-light",
      "bg-gray-active",
      "bg-teal-gradient",
      "bg-light-blue-gradient",
      "bg-blue-gradient",
      "bg-aqua-gradient",
      "bg-yellow-gradient",
      "bg-purple-gradient",
      "bg-green-gradient",
      "bg-red-gradient",
      "bg-black-gradient",
      "bg-maroon-gradient",
    ],
];
